### ISSUE TITLE
MS Word to Text

### ISSUE THREAD

**Issue by chmbrlnd** [CourseReps/ECEN303-Summer2015#2]
Hi Audrey,

You committed your file as a Word document. It should be in the form of a text document. You can look at the contributions from other students to get an idea. Can you please change that.

Best regards,
Jean-Francois Chamberland

**Comment by ahbarber7** [comment]
Hi,
I tried to do that previously and looked at multiple tutorials but could
not figure out how to do this, I was hoping to ask you today in class but I
think there was a confusion in class times because other classmates were
there but then another class was scheduled for that room and we had to
leave. Hopefully you can offer assistance in this tomorrow, but I'll try
again today and hopefully finally figure it out.

- Audrey Barber

**Comment by ValerieLynn25** [comment]
Audrey,
 I believe your default text editing should be vim. I set my as that just in case, but it should have it as that by default. If you are doing it on terminal, try creating the file in your directory with " echo 'random text'  > README.md" and then "open README.md" and just put in there the following:
#Identity
*Name:
*GitHubID:
*NetID:

Then save it, close it, and add it to the staging part, then commit it, then push it!
