### ISSUE TITLE
Challenge 4 error 

### ISSUE THREAD

**Issue by s34e32s21** [CourseReps/ECEN303-Summer2015#7]
There is several of us who are getting an error in the given code for challenge 4. Specifically, there is a unsupported operand error when we try to run: return math.floor(inputsymbol + channelnoise)
has anyone found a solution to this error?

**Comment by ValerieLynn25** [comment]
Specifically, our error looks like this when inputing your code:
dhcp-10-202-33-188:Challenges NCC-1701A$ python Challenge_4.py
Traceback (most recent call last):
  File "Challenge_4.py", line 19, in <module>
    receivedmessage.append(channel(message[messageindex]))
  File "Challenge_4.py", line 15, in channel
    return math.floor(inputsymbol + channelnoise)
TypeError: unsupported operand type(s) for +: 'function' and 'float'

**Comment by s34e32s21** [comment]
I think its because message is an array of memory locations not actual integer values. So the computer is seeing that line as a memory location plus a integer which the compiler doesn't understand.

**Comment by chmbrlnd** [comment]
Hello,

There was another issue with the Python code I provided for Challenge 4. This issue was fixed in class on Thursday. The sample code has been updated on GitHub.

 message = []
 for messageindex in range(0, 100):
-    message.append(messagebit)
+    message.append(messagebit())

Best regards,
Jean-Francois Chamberland
